

redis:
 redis_password: very-strong
 database_service_name: quotes-store
 redis_version: -6-c9s:c9s

quotes:
  image: registry.ocp4.example.com:8443/redhattraining/ocpdev-redis-quotes:4.18
  import:
    enabled: true
